add docker end env file
codingpot/pr12er pull request #16
Opened 2021-05-25 06:02 UTC by mrchypark

2021-05-25 06:07 UTC, kkweon requested changes

2021-05-25 06:07 UTC, kkweon commented on server/pkg/env/env.go
> +	ServiceAddress = getEnvVar("PR12ER_GRPC_PORT", "9000")
```suggestion
	ServicePort = getEnvVar("PR12ER_GRPC_PORT", "9000")
```

2021-05-25 06:07 UTC, kkweon commented on server/cmd/server/main.go
> +	fmt.Printf("Grpc server start! ver: %s\n", env.Nversion)
listening port 도 적어주심이

2021-05-27 10:09 UTC, mrchypark commented
@kkweon fly 설정 파일(이미지 배포로 작성 - 아직 이미지 생성 안 넣음) 추가하고 도커 파일 추가했습니다.

env는 제안 주신거 반영했어요

2021-05-27 13:39 UTC, kkweon commented on workspace.code-workspace
> +{
이 파일 꼭 필요하신가요?

2021-05-27 13:49 UTC, mrchypark commented on workspace.code-workspace
> +{
서버 폴더 환경 켜주는 파일이라 넣는데, 빼시죠.

2021-05-27 13:57 UTC, merged

2021-05-27 20:32 UTC, kkweon commented on server/deploy/Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-w -s -X 'github.com/codingpot/pr12er/server.pkg.env.Version=${APP_VERSION}'" -o service server/cmd/server/main.go
이거 빌드 되시나요? 전 안되네요.

현재 살펴보시면 아래와 같은 잘못된 구조가 나오게 됩니다.

```
/src/go.mod
/src/go.sum
/src/server/cmd/...
/src/server/pkg/...
```

Go 모듈은 server 디렉토리가 Go 모듈입니다.

```
/src/go.mod
/src/go.sum
/src/cmd/...
/src/pkg/...
```
(현재 프로젝트 구조 참조)



아래와 같이 수정하면 작동합니다. 

```diff
-COPY . .
-RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-w -s -X 'github.com/codingpot/pr12er/server.pkg.env.Version=${APP_VERSION}'" -o service server/cmd/server/main.go
+ADD ./server .
+RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-w -s -X 'github.com/codingpot/pr12er/server.pkg.env.Version=${APP_VERSION}'" -o service cmd/server/main.go
```