33 feature add youtube view
codingpot/pr12er pull request #35
Opened 2021-05-30 15:48 UTC by deep-diver

2021-05-30 19:48 UTC, kkweon commented
Update minsdkversion https://github.com/codingpot/pr12er/blob/c2fcec29c02f5ec6d80b2e271da3857a5c95c0b0/client/android/app/build.gradle#L38

lets use 20

2021-05-30 22:21 UTC, kkweon requested changes

2021-05-30 22:21 UTC, kkweon commented on client/lib/main.dart
> +      Category category, String url) {
Parameter가 많아질때는 named parameters를 이용합니다.

2021-05-31 15:14 UTC, deep-diver commented
@kkweon please review this PR again

2021-05-31 17:23 UTC, kkweon approved these changes
수고하셨습니다.

2021-05-31 17:23 UTC, kkweon commented on client/lib/detail.dart
> +        handleColor: Colors.transparent,
# 이번 앱은 연습이나 마찬가지기 때문에 바꾸실 필요 없습니다.

Just FYI,
Flutter는 색을 이렇게 직접 지정(e.g., `Colors.redAccent`) 해서 거의 쓰지 않습니다.

대신에 `Theme` 을 활용합니다.

```dart
Theme.of(context).accentColor
Theme.of(context).primaryColor
Theme.of(context).backgroundColor
```

이런식으로 하고 앱 레벨에서 `Theme` 으로 콘트롤 합니다.

```dart
MaterialApp(
  theme: ThemeData(
    // Define the default brightness and colors.
    brightness: Brightness.dark,
    primaryColor: Colors.lightBlue[800],
    accentColor: Colors.cyan[600],

    // Define the default font family.
    fontFamily: 'Georgia',

    // Define the default TextTheme. Use this to specify the default
    // text styling for headlines, titles, bodies of text, and more.
    textTheme: TextTheme(
      headline1: TextStyle(fontSize: 72.0, fontWeight: FontWeight.bold),
      headline6: TextStyle(fontSize: 36.0, fontStyle: FontStyle.italic),
      bodyText2: TextStyle(fontSize: 14.0, fontFamily: 'Hind'),
    ),
  ),
);
```

이렇게 하드코딩할 경우 다크모드 지원은 어렵습니다.

2021-05-31 17:24 UTC, merged