feat: initial implement of the gRPC middleware - logrus, prometheus
codingpot/pr12er pull request #44
Opened 2021-06-02 06:34 UTC by nicewook

2021-06-02 07:09 UTC, kkweon requested changes
다음번엔는 기능 단위 PR (prom따로 logging 따로) 부탁드립니다.

2021-06-02 07:26 UTC, nicewook commented on server/cmd/server/main.go
> +	promServer = &http.Server{Handler: promhttp.HandlerFor(reg, promhttp.HandlerOpts{}), Addr: fmt.Sprintf("0.0.0.0:%d", 9092)}
env.ServicePort 를 참고하여 env.PrometheusPort로 하면 될까요?

2021-06-02 07:30 UTC, nicewook commented on server/cmd/server/main.go
> +	customizedCounterMetric = prometheus.NewCounterVec(prometheus.CounterOpts{
네~

2021-06-02 07:31 UTC, nicewook commented on .vscode/settings.json
> +}
넵~

2021-06-02 08:13 UTC, kkweon approved these changes
수고하셨습니다.

2021-06-02 15:21 UTC, kkweon commented
도움이 필요하신가요?

2021-06-03 01:21 UTC, nicewook commented
그냥 머지하면 되려나요? 
1. 어제는 그 순간에 resolve가 안된다고 팝업이 떴었습니다
2. server/go.sum conflict가 난다고 하는데 그냥 머지해도 되려나요?

2021-06-03 02:50 UTC, kkweon commented
아니요 수정하셔야 됨니당 껄껄껄

2021-06-03 02:51 UTC, kkweon commented
대신 해드릴수도 있으니까 필요하시면 말씀하세요

2021-06-03 03:11 UTC, merged

2021-06-03 11:13 UTC, nicewook commented
감사합니다