feat: serving GPRC GetVideos using dumped pdtxt
codingpot/pr12er pull request #55
Opened 2021-06-06 01:25 UTC by nicewook

- client/main.go can test this GRPC function and save response as .pbtxt

2021-06-06 06:10 UTC, kkweon requested changes

2021-06-06 06:10 UTC, kkweon commented on server/pkg/serv/serv.go
> +	if err := prototext.Unmarshal(internal.PR12MetadataProtoText, &metadataDump); err != nil {
https://github.com/codingpot/pr12er/blob/8dd3b6e2dc77541ac7ae37a3ada8672995b5a196/server/internal/pr12_metadata.go#L19

함수 사용하시면 됩니다.

2021-06-06 06:10 UTC, kkweon commented on server/pkg/serv/serv.go
> +		// video.NumberOfLike
```suggestion
```

2021-06-06 06:10 UTC, kkweon commented on server/pkg/serv/serv.go
> +func getVideosFromDumpedPbtxt() (pr12er.GetVideosResponse, error) {
```suggestion
func getVideosFromDumpedPbtxt() (*pr12er.GetVideosResponse, error) {
```

2021-06-06 06:10 UTC, kkweon commented on server/pkg/serv/serv.go
> +	return &resp, err
```suggestion
	return getVideosFromDumpedPbtxt()
```

2021-06-06 06:10 UTC, kkweon commented on server/pkg/serv/serv.go
> +		video.Id = metadata.Id
```suggestion
		video.Id = metadata.GetId()
```

이 경우에는 다를게 없지만 프로토콜버퍼는 Getter 를 사용해주는게 컨벤션입니다. (safeer)
Nested Object의 경우 로직이 들어가있습니다.

2021-06-06 06:10 UTC, kkweon commented on server/cmd/client/main.go
>  package main
evans 한번 사용해보세요. 자동완성 지원됨

```shell
evans --reflection --host ingress-kkweon.cloud.okteto.net -p 443 repl
```

2021-06-06 14:25 UTC, nicewook commented on server/cmd/client/main.go
>  package main
키워드 확인해보겠습니다. 감사합니다. @@

2021-06-06 14:30 UTC, nicewook commented on server/cmd/client/main.go
>  package main
이게 정확히 뭔지 조금만 더 가이드 부탁드려도 될까요?

2021-06-06 14:31 UTC, nicewook commented on server/cmd/client/main.go
> +		if err := os.WriteFile("pr12_getvideos.pbtxt", []byte(respVideosStr), 0666); err != nil {
```suggestion
		if err := os.WriteFile("pr12_getvideos.pbtxt", []byte(respVideosStr), 0600); err != nil {
```

2021-06-06 14:35 UTC, nicewook commented on server/cmd/client/main.go
> +
```suggestion
```

2021-06-06 14:37 UTC, nicewook commented on server/cmd/client/main.go
> +			log.Fatal(err)
```suggestion
			log.WithError(err).Fatal("Error on writing file pr12_getvideos.pbtxt")
```

2021-06-06 14:46 UTC, nicewook commented on server/pkg/serv/serv.go
> +	if err := prototext.Unmarshal(internal.PR12MetadataProtoText, &metadataDump); err != nil {
```suggestion
	var resp pr12er.GetVideosResponse
	metadataDump := internal.ReadPR12MetadataProtoText()
```

2021-06-06 14:48 UTC, nicewook commented on server/pkg/serv/serv.go
> +	if err := prototext.Unmarshal(internal.PR12MetadataProtoText, &metadataDump); err != nil {
이거 봤으면서도 확인안했네요.

2021-06-06 14:49 UTC, nicewook commented on server/pkg/serv/serv.go
> +	return resp, nil
```suggestion
	return &resp, nil
```

2021-06-06 14:51 UTC, nicewook commented on server/pkg/serv/serv.go
> +		log.Fatal(err)
```suggestion
		log.WithError(err).Panic("Error while writing file named pr12_getvideos.pbtxt")
```

2021-06-06 14:56 UTC, nicewook commented
1. 말씀하신 부분 참고하여 반영하였습니다.
2. golangci-lint 에서 no such linter "godox" 라는 에러가 나면서 린트가 안되네요. 집 컴터에서만 안되는데 이거 이유를 모르겠네요
3. evans 는 좀더 찾아보겠습니다. 리뷰 감사합니다.

2021-06-06 21:54 UTC, kkweon approved these changes
아주 멋지네요. 👏 👏 👏 

린트에러 및 비디오 객체 생성 관련 수정만 해주시면 머지하겠습니다.

2021-06-06 21:54 UTC, kkweon commented on server/pkg/serv/serv.go
> +		resp.Videos = append(resp.Videos, &video)
```suggestion
		video := &pr12er.Video{
			Id:           metadata.GetId(),
			Title:        metadata.GetTitle(),
			Presenter:    metadata.GetPresenter(),
			Keywords:     metadata.GetKeywords(),

			// TODO: Update category and number of likes.
			Category:     pr12er.Category_CATEGORY_UNSPECIFIED,
			NumberOfLike: 0,
		}

		if len(metadata.GetVideoMetadata()) > 0 {
			video.Link = metadata.GetVideoMetadata()[0].Url
		}

		resp.Videos = append(resp.Videos, video)
```

2021-06-07 01:24 UTC, nicewook commented on server/pkg/serv/serv.go
> +		resp.Videos = append(resp.Videos, &video)
눈이 화악 밝아집니다. 제 기존 습관보다 훨 좋아보이네요.

2021-06-07 03:51 UTC, merged

2021-06-07 03:52 UTC, kkweon commented
수고하셨습니다

2021-06-07 03:54 UTC, nicewook commented
감사합니다. (__)